<div class="art-Block"><div class="art-Block-tl"></div><div class="art-Block-tr"></div><div class="art-Block-bl"></div><div class="art-Block-br"></div><div class="art-Block-tc"></div><div class="art-Block-bc"></div><div class="art-Block-cl"></div><div class="art-Block-cr"></div><div class="art-Block-cc"></div><div class="art-Block-body"><div class="art-BlockHeader"><div class="l"></div><div class="r"></div><div class="art-header-tag-icon"><div class="t">
<?php _e('Featured Posts', 'kubrick'); ?>
</div></div></div><div class="art-BlockContent"><div class="art-BlockContent-body">
<?php include (ABSPATH . '/wp-content/plugins/featured-content-gallery/gallery.php'); ?>
<div class="cleared"></div></div></div><div class="cleared"></div></div></div>